# Generated by Django 2.0.7 on 2018-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=100000)),
                ('from_address', models.CharField(max_length=150)),
                ('to_address', models.CharField(max_length=150)),
            ],
        ),
    ]
